"""add email, sex, contact phone, photo url, and is_claimed"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5c2160fb215'
down_revision: Union[str, None] = '8c2b8cc3d2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cell_groups', 'location')
    op.add_column('users', sa.Column('contact_person_phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('sex', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('profile_photo_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('is_claimed', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('users_serial_number_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_serial_number'), table_name='users')
    op.create_index(op.f('ix_users_serial_number'), 'users', ['serial_number'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_serial_number'), table_name='users')
    op.create_index(op.f('ix_users_serial_number'), 'users', ['serial_number'], unique=False)
    op.create_unique_constraint(op.f('users_serial_number_key'), 'users', ['serial_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'is_claimed')
    op.drop_column('users', 'profile_photo_url')
    op.drop_column('users', 'sex')
    op.drop_column('users', 'email')
    op.drop_column('users', 'contact_person_phone')
    op.add_column('cell_groups', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
